# Generated by Django 3.2 on 2022-06-20 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_photo', models.ImageField(upload_to='cloth/')),
                ('description', tinymce.models.HTMLField()),
                ('size', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Sell', 'Sell'), ('Donation', 'Donation')], default='sell', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='medicalservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicalservices', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(null=True, upload_to='profiles/')),
                ('contact', models.CharField(max_length=12)),
                ('service', models.CharField(choices=[('Driver', 'Driver'), ('Doctor', 'Doctor'), ('Cleaner', 'Cleaner'), ('Teacher', 'Teacher'), ('Sponsor', 'Sponsor'), ('Motivator', 'Motivator')], default='Driver', max_length=15)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('bio', tinymce.models.HTMLField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('motiv_photo', models.ImageField(upload_to='motive/')),
                ('motivation', tinymce.models.HTMLField()),
                ('target', models.CharField(choices=[('Kids', 'Kids'), ('Youth', 'Youth'), ('Couples', 'Couples'), ('Singles', 'Singles'), ('Aged Groups', 'Aged Groups')], default='kids', max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_photo', models.ImageField(upload_to='medical/')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('medicalservices', models.ManyToManyField(to='community.medicalservices')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.cloth')),
                ('motive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.motivation')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
