# Generated by Django 3.2 on 2022-06-21 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='service/')),
                ('description', tinymce.models.HTMLField()),
                ('target', models.CharField(choices=[('Kids', 'Kids'), ('Youth', 'Youth'), ('Couples', 'Couples'), ('Singles', 'Singles'), ('Aged Groups', 'Aged Groups')], default='kids', max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='motive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.services'),
        ),
        migrations.DeleteModel(
            name='Motivation',
        ),
    ]
