# Generated by Django 3.2 on 2022-06-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20220621_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='category',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Donate', 'Donate')], default='sell', max_length=15),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.CharField(choices=[('XSmall', 'XSmall'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('XLarge', 'XLarge')], default='kids', max_length=15),
        ),
    ]
