# Generated by Django 3.2 on 2022-06-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20220621_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='target',
        ),
        migrations.AddField(
            model_name='services',
            name='available',
            field=models.CharField(choices=[('6:00AM', '9:00AM'), ('9:01AM', '12:00NOON'), ('12:01PM', '3:00PM'), ('3:01PM', '6:00PM'), ('6:01PM', '9:00PM'), ('Emmergencies', 'Emmergencies')], default='kids', max_length=15),
        ),
    ]
