# Generated by Django 3.2 on 2022-06-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_medical_daktari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='category',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Donate', 'Donate')], default='sell', max_length=15),
        ),
    ]
