# Generated by Django 3.2 on 2022-06-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_cloth_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='service',
            field=models.CharField(choices=[('Driver', 'Driver'), ('Doctor', 'Doctor'), ('Cleaner', 'Cleaner'), ('Teacher', 'Teacher'), ('Sponsor', 'Sponsor'), ('Motivator', 'Motivator'), ('Member', 'Member')], default='Driver', max_length=15),
        ),
    ]
