# Generated by Django 3.2 on 2022-06-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_profile_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='name',
            new_name='Service',
        ),
    ]
