# Generated by Django 3.2 on 2022-06-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220622_0359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
